allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true

overrides:
  form-data: 4.0.6
  tmp: 0.2.7
  builder-util-runtime: 9.7.0
  brace-expansion@1: 1.1.16
  brace-expansion@2: 2.1.2
  brace-expansion@5: 5.0.9
